-- Drop tables if they exist
DROP TABLE SPRING_SESSION_ATTRIBUTES CASCADE CONSTRAINTS;
DROP TABLE SPRING_SESSION CASCADE CONSTRAINTS;
DROP TABLE ADDRESSES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP SEQUENCE ADDRESSES_SEQ;

-- Create sequence for ADDRESSES auto-increment
CREATE SEQUENCE ADDRESSES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Create USERS table with composite primary key (USERNAME + EMAIL)
CREATE TABLE USERS (
    USERNAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    FIRST_NAME VARCHAR2(255) NOT NULL,
    LAST_NAME VARCHAR2(255) NOT NULL,
    PHONE_NUMBER VARCHAR2(50),
    STATUS VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USERNAME, EMAIL)
);

-- Create ADDRESSES table
CREATE TABLE ADDRESSES (
    ADDRESS_ID NUMBER(19) NOT NULL,
    USERNAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    ADDRESS_LINE1 VARCHAR2(500) NOT NULL,
    ADDRESS_LINE2 VARCHAR2(500),
    CITY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100) NOT NULL,
    ZIP_CODE VARCHAR2(20) NOT NULL,
    COUNTRY VARCHAR2(100) NOT NULL,
    ADDRESS_TYPE VARCHAR2(50) NOT NULL,
    IS_DEFAULT NUMBER(1) NOT NULL,
    CONSTRAINT PK_ADDRESSES PRIMARY KEY (ADDRESS_ID),
    CONSTRAINT FK_ADDRESSES_USER FOREIGN KEY (USERNAME, EMAIL) REFERENCES USERS(USERNAME, EMAIL) ON DELETE CASCADE,
    CONSTRAINT CHK_IS_DEFAULT CHECK (IS_DEFAULT IN (0, 1))
);

-- Create indexes
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_ADDRESSES_USER ON ADDRESSES(USERNAME, EMAIL);
CREATE INDEX IDX_ADDRESSES_DEFAULT ON ADDRESSES(USERNAME, EMAIL, IS_DEFAULT);
CREATE INDEX IDX_ADDRESSES_TYPE ON ADDRESSES(ADDRESS_TYPE);

-- Create Spring Session tables
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME NUMBER(19) NOT NULL,
    LAST_ACCESS_TIME NUMBER(19) NOT NULL,
    MAX_INACTIVE_INTERVAL NUMBER(10) NOT NULL,
    EXPIRY_TIME NUMBER(19) NOT NULL,
    PRINCIPAL_NAME VARCHAR2(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR2(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

-- Insert sample data (India)
INSERT INTO USERS (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('raj_kumar', 'raj.kumar@example.com', 'Raj', 'Kumar', '+919876543210', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO USERS (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('priya_sharma', 'priya.sharma@example.com', 'Priya', 'Sharma', '+919123456789', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO ADDRESSES (ADDRESS_ID, USERNAME, EMAIL, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP_CODE, COUNTRY, ADDRESS_TYPE, IS_DEFAULT)
VALUES (ADDRESSES_SEQ.NEXTVAL, 'raj_kumar', 'raj.kumar@example.com', 'Flat 301, Sunrise Apartments', 'MG Road', 'Bangalore', 'Karnataka', '560001', 'India', 'SHIPPING', 1);

INSERT INTO ADDRESSES (ADDRESS_ID, USERNAME, EMAIL, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP_CODE, COUNTRY, ADDRESS_TYPE, IS_DEFAULT)
VALUES (ADDRESSES_SEQ.NEXTVAL, 'raj_kumar', 'raj.kumar@example.com', 'Plot 45, Sector 18', 'Near Metro Station', 'Gurgaon', 'Haryana', '122001', 'India', 'BILLING', 0);

INSERT INTO ADDRESSES (ADDRESS_ID, USERNAME, EMAIL, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, ZIP_CODE, COUNTRY, ADDRESS_TYPE, IS_DEFAULT)
VALUES (ADDRESSES_SEQ.NEXTVAL, 'priya_sharma', 'priya.sharma@example.com', 'House No 12, Andheri West', NULL, 'Mumbai', 'Maharashtra', '400058', 'India', 'SHIPPING', 1);

COMMIT;

-- Verify data
SELECT * FROM USERS;
SELECT * FROM ADDRESSES;
