-- Sequences
CREATE SEQUENCE IF NOT EXISTS USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ADDRESSES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CATEGORIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PRODUCTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PRODUCT_IMAGES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS DISCOUNTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS INVENTORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS INVENTORY_RESERVATIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CARTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CART_ITEMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ORDERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ORDER_ITEMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PAYMENTS_SEQ START WITH 1 INCREMENT BY 1;

-- Tables
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID       BIGINT NOT NULL DEFAULT NEXT VALUE FOR USERS_SEQ PRIMARY KEY,
    USERNAME      VARCHAR(255) NOT NULL UNIQUE,
    EMAIL         VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME    VARCHAR(255) NOT NULL,
    LAST_NAME     VARCHAR(255) NOT NULL,
    PHONE_NUMBER  VARCHAR(50),
    STATUS        VARCHAR(50)  NOT NULL,
    CREATED_AT    TIMESTAMP    NOT NULL,
    UPDATED_AT    TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESSES (
    ADDRESS_ID    BIGINT NOT NULL DEFAULT NEXT VALUE FOR ADDRESSES_SEQ PRIMARY KEY,
    USER_ID       BIGINT NOT NULL,
    ADDRESS_LINE1 VARCHAR(500) NOT NULL,
    ADDRESS_LINE2 VARCHAR(500),
    CITY          VARCHAR(100) NOT NULL,
    STATE         VARCHAR(100) NOT NULL,
    ZIP_CODE      VARCHAR(20)  NOT NULL,
    COUNTRY       VARCHAR(100) NOT NULL,
    ADDRESS_TYPE  VARCHAR(50)  NOT NULL,
    IS_DEFAULT    BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_ID        BIGINT NOT NULL DEFAULT NEXT VALUE FOR CATEGORIES_SEQ PRIMARY KEY,
    NAME               VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION        VARCHAR(1000),
    PARENT_CATEGORY_ID BIGINT,
    IMAGE_URL          VARCHAR(500),
    DISPLAY_ORDER      INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID   BIGINT         NOT NULL DEFAULT NEXT VALUE FOR PRODUCTS_SEQ PRIMARY KEY,
    NAME         VARCHAR(255)   NOT NULL,
    DESCRIPTION  VARCHAR(2000),
    SKU          VARCHAR(255)   NOT NULL UNIQUE,
    PRICE        DECIMAL(19,2)  NOT NULL,
    BRAND        VARCHAR(255)   NOT NULL,
    CATEGORY_ID  BIGINT         NOT NULL,
    RATING       DOUBLE,
    REVIEW_COUNT INT            NOT NULL,
    STATUS       VARCHAR(50)    NOT NULL,
    CREATED_AT   TIMESTAMP      NOT NULL,
    UPDATED_AT   TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_IMAGES (
    IMAGE_ID      BIGINT       NOT NULL DEFAULT NEXT VALUE FOR PRODUCT_IMAGES_SEQ PRIMARY KEY,
    PRODUCT_ID    BIGINT       NOT NULL,
    IMAGE_URL     VARCHAR(500) NOT NULL,
    DISPLAY_ORDER INT          NOT NULL DEFAULT 0,
    IS_PRIMARY    BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS DISCOUNTS (
    DISCOUNT_ID  BIGINT        NOT NULL DEFAULT NEXT VALUE FOR DISCOUNTS_SEQ PRIMARY KEY,
    PRODUCT_ID   BIGINT        NOT NULL,
    DISCOUNT_PCT DECIMAL(5,2)  NOT NULL,
    START_DATE   TIMESTAMP     NOT NULL,
    END_DATE     TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS INVENTORY (
    INVENTORY_ID       BIGINT       NOT NULL DEFAULT NEXT VALUE FOR INVENTORY_SEQ PRIMARY KEY,
    PRODUCT_ID         BIGINT       NOT NULL UNIQUE,
    SKU                VARCHAR(255) NOT NULL UNIQUE,
    TOTAL_QUANTITY     INT          NOT NULL,
    AVAILABLE_QUANTITY INT          NOT NULL,
    RESERVED_QUANTITY  INT          NOT NULL,
    MIN_STOCK_LEVEL    INT          NOT NULL,
    WAREHOUSE_LOCATION VARCHAR(255),
    LAST_UPDATED       TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS INVENTORY_RESERVATIONS (
    RESERVATION_ID BIGINT    NOT NULL DEFAULT NEXT VALUE FOR INVENTORY_RESERVATIONS_SEQ PRIMARY KEY,
    INVENTORY_ID   BIGINT    NOT NULL,
    ORDER_ID       BIGINT    NOT NULL,
    QUANTITY       INT       NOT NULL,
    EXPIRES_AT     TIMESTAMP NOT NULL,
    CREATED_AT     TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CARTS (
    CART_ID    BIGINT    NOT NULL DEFAULT NEXT VALUE FOR CARTS_SEQ PRIMARY KEY,
    USER_ID    BIGINT    NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CART_ITEMS (
    CART_ITEM_ID BIGINT    NOT NULL DEFAULT NEXT VALUE FOR CART_ITEMS_SEQ PRIMARY KEY,
    CART_ID      BIGINT    NOT NULL,
    PRODUCT_ID   BIGINT    NOT NULL,
    QUANTITY     INT       NOT NULL,
    ADDED_AT     TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID              BIGINT        NOT NULL DEFAULT NEXT VALUE FOR ORDERS_SEQ PRIMARY KEY,
    ORDER_NUMBER          VARCHAR(100)  NOT NULL UNIQUE,
    USER_ID               BIGINT        NOT NULL,
    TOTAL_AMOUNT          DECIMAL(19,2) NOT NULL,
    ORDER_STATUS          VARCHAR(50)   NOT NULL,
    ORDER_DATE            TIMESTAMP     NOT NULL,
    SHIPPING_ADDRESS_LINE1 VARCHAR(500) NOT NULL,
    SHIPPING_ADDRESS_LINE2 VARCHAR(500),
    SHIPPING_CITY         VARCHAR(100)  NOT NULL,
    SHIPPING_STATE        VARCHAR(100)  NOT NULL,
    SHIPPING_ZIP_CODE     VARCHAR(20)   NOT NULL,
    SHIPPING_COUNTRY      VARCHAR(100)  NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID    BIGINT        NOT NULL DEFAULT NEXT VALUE FOR ORDER_ITEMS_SEQ PRIMARY KEY,
    ORDER_ID         BIGINT        NOT NULL,
    PRODUCT_ID       BIGINT        NOT NULL,
    PRODUCT_NAME     VARCHAR(255)  NOT NULL,
    SKU              VARCHAR(255)  NOT NULL,
    QUANTITY         INT           NOT NULL,
    ORIGINAL_PRICE   DECIMAL(19,2) NOT NULL,
    DISCOUNTED_PRICE DECIMAL(19,2) NOT NULL,
    FINAL_PRICE      DECIMAL(19,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID         BIGINT       NOT NULL DEFAULT NEXT VALUE FOR PAYMENTS_SEQ PRIMARY KEY,
    ORDER_ID           BIGINT       NOT NULL UNIQUE,
    ORDER_NUMBER       VARCHAR(100) NOT NULL,
    RAZORPAY_ORDER_ID  VARCHAR(255) NOT NULL,
    RAZORPAY_PAYMENT_ID VARCHAR(255),
    AMOUNT             BIGINT       NOT NULL,
    CURRENCY           VARCHAR(10)  NOT NULL,
    STATUS             VARCHAR(50)  NOT NULL,
    PAYMENT_DATE       TIMESTAMP    NOT NULL
);
